authapp/urls.py
from django.urls import path

from . import views

app_name = 'authapp'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('signin/', views.signin, name='signin'),
    path('logout/', views.logoutuser, name='logout'),
    path('profile/', views.profile, name='profile')
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

tkppwa05/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authapp.urls')),
    path('', include('about.urls')),
    path('', include('infocorona.urls')),
    path('', include('myfootprints.urls')),
    path('', include('covid19App.urls')),
]

authapp/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    full_name = models.CharField(max_length=50)

    def __str__(self):
        return self.user.username   

authapp/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from . import models

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class  UserProfileForm(ModelForm):
    class Meta:
        model = models.UserProfile
        fields = ['full_name']

        # full_name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'placeholder':'full name'}))
        widget = {
            'full_name': forms.TextInput(attrs={'placeholder': 'name'}),
        }

authapp/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from django.http import JsonResponse
from . import forms, models
from myfootprints.models import MyFootPrints

def signup(request):
    user_form = forms.CreateUserForm()
    profile_form = forms.UserProfileForm()

    if request.method == 'POST':
        user_form = forms.CreateUserForm(request.POST)
        profile_form = forms.UserProfileForm(request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.save()
            profile = profile_form.save()
            profile.user = user
            profile.save()
            username = user_form.cleaned_data.get('username')
            messages.success(request, 'Account was created for ' + username)
            return JsonResponse({'success':'success'})
    context = { 
        'form':user_form,
        'profile_form':profile_form,
    }
    return render(request, 'authapp/signup.html', context)

def signin(request):
    if request.user.is_authenticated:
        return redirect('/')

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            login(request, user)
            return redirect(request.GET.get('next') or '/')
        else:
            messages.info(request, 'Username or Password is Incorrect')

    return render(request, 'authapp/signin.html')

def logoutuser(request):
    logout(request)
    return redirect('/auth/signin/')

@login_required(login_url='/auth/signin/')
def profile(request):
    profile_user = models.UserProfile.objects.get(user = request.user)
    total_footprints = MyFootPrints.objects.filter(user = request.user).count()
    data = {
        'profile_user' : profile_user,
        'total_footprints' : total_footprints
    }
    return render(request, 'authapp/profile.html', data)

authapp/templates/authapp/profile.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Profile</title>
<link rel="stylesheet" href="{% static 'css/auth.css' %}">
{% endblock meta %}

{% block sign %}{% endblock %}

{% block content %}
<div class="content">   
    <div class="profile">
        <h2>My Profile</h2>
        <table>
            <tr>
                <td>
                    Name
                </td>
                <td>
                    <p>: {{ profile_user.full_name }}</p>
                </td>
            </tr>
            <tr>
                <td>
                    Username
                </td>
                <td>
                    <p>: {{ user.get_username }}</p>
                </td>
            </tr>
            <tr>
                <td>
                    Email
                </td>
                <td>
                    <p>: {{ user.email }}</p>
                </td>
            </tr>
            <tr>
                <td>
                    Total Footprints
                </td>
                <td>
                    <p>: {{ total_footprints }}</p>
                </td>
            </tr>
        </table>
    </div>
</div>
{% endblock content %}

authapp/templates/authapp/signin.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Signin</title>
<link rel="stylesheet" href="{% static 'css/auth.css' %}">
{% endblock meta %}

{% block sign %}{% endblock %}

{% block content %}
  <div class="content">
    <div id="asset">
        <img class="invis" src="{% static 'img/Jendela1.svg' %}">
    </div>
    <div id="logindiv">   
        <h2>Sign in to your account</h2>
        <form id="loginform" method="POST" action="">
            {% csrf_token %}
            <input type="text" name="username" placeholder="Username">
            <label for="username">Username</label>
            <input type="password" name="password" placeholder="Password">
            <label for="password">Password</label>
            <input type="submit" value="Sign in">
            {% for message in messages %}
              <p class="errormsg">{{ message }}</p>
            {% endfor %}
        </form>
        <p class="hvacc">Didn't have any account yet? Sign up <a href="/auth/signup/">Here</a></p>
    </div>
  </div>
  <script type="text/javascript" >
    $(document).ready(function(){
      $(':input[type="submit"]').prop('disabled', true);
      $('input[type="text"]').keyup(function() {
        if($(this).val() != '') {
        $(':input[type="submit"]').prop('disabled', false);
        }
      });
    });
  </script>
{% endblock content %}

authapp/templates/authapp/signup.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Signup</title>
<link rel="stylesheet" href="{% static 'css/auth.css' %}">
{% endblock meta %}

{% block sign %}{% endblock %}

{% block content %}
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
  <div class="content">
    <div id="asset">
        <img class="invis" src="{% static 'img/Jendela2.svg' %}">
    </div>
    <div id="logindiv">   
      <h2>Create Account</h2>
        <form id="loginform" method="POST" action="#">
          {% csrf_token %}
          {{ form.non_field_errors }}
          {{ form.username.errors }}
          {{ form.username }}
          <label for="{{ form.username.id_for_label }}">Username</label>
          {{ profile_form.full_name}}
          <label for="{{ profile_form.full_name.id_for_label }}">Full Name</label>
          {{ form.email.errors }}
          {{ form.email }}
          <label for="{{ form.email.id_for_label }}">E-mail</label>
          {{ form.password1.errors }}
          {{ form.password1}}
          <label for="{{ form.password1.id_for_label }}">Password</label>
          {{ form.password2.errors }}
          {{ form.password2 }}
          <label for="{{ form.password2.id_for_label }}">Confirm Password</label>
          <input id="signup-btn" type="submit" value="Sign up">
        </form>
      <p class="hvacc">Already have an account? Sign in <a href="/auth/signin/">Here</a></p>
    </div>
  </div>
  <script type="text/javascript" >
    $(document).ready(function(){
      $("#id_username").attr('placeholder', 'Username');
      $("#id_email").attr('placeholder', 'E-mail');
      $("#id_full_name").attr('placeholder', 'Full Name');
      $("#id_password1").attr('placeholder', 'Password');
      $("#id_password2").attr('placeholder', 'Confirm Password');
      $("#signup-btn").click(function(event){
        if(validate()){
          $.ajax({
            type: "POST",
            url: "/auth/signup/",
            data: {
              username : $('#id_username').val(),
              email : $('#id_email').val(),
              full_name : $('#id_full_name').val(),
              password1 : $('#id_password1').val(),
              password2 : $('#id_password2').val(),
              csrfmiddlewaretoken : '{{ csrf_token }}',
            },
            success: function(res){
              window.location = "/auth/signin/";
            }
          });
        }
      });

      function validate(){
        var isValid = true;
        if(!$('#id_username').val()){
          isValid = false;
        }
        if(!$('#id_email').val()){
          isValid = false;
        }
        else{
          if(!(/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/.test($('#id_email').val()))){
            isValid = false;
          }
        }
        if(!$('#id_full_name').val()){
          isValid = false;
        }
        if(!$('#id_password1').val() && !$('#id_password2').val()){
          isValid = false;
        }
        else{
          if($('#id_password1').val() != $('#id_password2').val()){
            isValid = false;
          }
        }
        return isValid;
      }
    });
  </script>
{% endblock content %}