main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

myfootprints/urls.py
from django.urls import path

from . import views

app_name = 'myfootprints'

urlpatterns = [
    path('my-footprints/', views.myfootprints, name='myfootprints'),
    path('add-place/', views. addplace, name='addfootprints'),
    path('delete-place/<int:id>', views.delete, name="delete-place"),
    path('update-place/<int:id>', views.update, name='update-place'),
]

tkppwa05/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authapp.urls')),
    path('', include('about.urls')),
    path('', include('infocorona.urls')),
    path('', include('myfootprints.urls')),
    path('', include('covid19App.urls')),
]

myfootprints/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class MyFootPrints(models.Model):
    place = models.CharField(max_length=100)
    date = models.DateField()
    desc = models.CharField(max_length=280)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    
    def __str__(self):
        return self.place

myfootprints/forms.py
from django import forms

from .models import MyFootPrints

class MyFootPrintsForm(forms.ModelForm):
    place = forms.CharField()
    date = forms.DateField()
    desc = forms.CharField()
    
    class Meta:
        model = MyFootPrints
        fields = ('place', 'date', 'desc')

myfootprints/views.py
from django.shortcuts import render, redirect
from .models import MyFootPrints
from .forms import MyFootPrintsForm
import datetime

# Create your views here.

def myfootprints(request):
    places = MyFootPrints.objects.filter(user=request.user)
    return render(request, 'myfootprints.html', {'places':places})

def addplace(request):
    form = MyFootPrintsForm()
    if request.method == 'POST':
        form = MyFootPrintsForm(request.POST)
        place = request.POST['place']
        date_time_str = request.POST['date']
        desc = request.POST['desc']
        if form.is_valid():
            user = request.user
            date_time_obj = datetime.datetime.strptime(date_time_str, '%m/%d/%Y')
            fp = MyFootPrints(place=place, date=date_time_obj, desc=desc, user=user)
            fp.save()
            # form.save()
            return redirect('/my-footprints')
    return render(request, 'addplace.html', {'form':form})

def update(request, id):
    place = MyFootPrints.objects.get(id=id)
    form = MyFootPrintsForm(instance=place)
    if request.method == 'POST':
        form = MyFootPrintsForm(request.POST, instance=place)
        if form.is_valid():
            form.save()
            return redirect('/my-footprints')
    return render(request, 'addplace.html', {'form':form})

def delete(request, id):
    place = MyFootPrints.objects.get(id=id)
    place.delete()
    return redirect('/my-footprints')

myfootprints/templates/addplace.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Add Place</title>
<link rel="stylesheet" href="{% static 'css/auth.css' %}">
<link rel="stylesheet" href="{% static 'css/addplace.css' %}">
{% endblock meta %}

{% block content %}
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <div class="content">
        <div id="asset">
            <img class="invis" src="{% static 'img/Cat.svg' %}">
        </div>
        <div id="logindiv">
            <h2>Where have you been?</h1>
                <form id="loginform" method='POST'>
                    {% csrf_token %}
                    {{ form.place }}
                    <label for="{{ form.place.id_for_place }}">Place</label>
                    {{ form.date }}
                    <label for="{{ form.date.id_for_date }}" type="date">Date</label>
                    {{ form.desc }}
                    <label for="{{ form.desc.id_for_date }}">Description</label>
                    <button type="submit" class="btn btn-submit">Submit</button>
                </form>
        </div>
    </div>

    <script type="text/javascript" >
    $(document).ready(function(){
        $("#id_place").attr('placeholder', 'Place');
        $("#id_date").attr('placeholder', 'Date (mm/dd/yyyy)');
        $("#id_desc").attr('placeholder', 'Description');
    });
    </script>
    
    <!--
    <div class="container-fluid">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <img class="img-responsive img-center" src="{% static 'img/Cat.svg' %}">
                </div>
                <div class="col-md-6" id="logindiv">
                    <div class="logindiv">
                        
                            <h1 class="card-title">Where have you been?</h1>
                        
                        
                        <form method="POST">
                            {% csrf_token %}
                            {{ form.place }}
                            <label for="{{ form.place.id_for_place }}">Place</label>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div> -->
{% endblock content %}

myfootprints/templates/myfootprints.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>My Footprints</title>
<link rel="stylesheet" href="{% static 'css/myfootprints.css' %}">
{% endblock meta %}

{% block content %}



<div class="container-fluid">
    <div class="container">
        {% if not places %}
        <div class="row>"
        <div class="col-md-12">
            <h1 style="font-family: 'Rubik Black';
    font-style: normal;
    font-weight: 900;
    font-size: 44px;
    line-height: 79px;
    text-align: center;
    color: #438A5E;">Looks like you don't have any footprints</h1>
            <br>
            <p style="font-family: Poppins;
    font-style: normal;
    font-weight: 600;
    font-size: 34.4941px;
    line-height: 79px;
    text-align: center;
    color: #436F8A;">Let's create one!</p>
            <br><br>
        </div>
        </div>

        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <table style="margin-right:auto;margin-left:auto;">
                    <tr>
                        <td>
                            <a href="{% url 'myfootprints:addfootprints' %}"><button class="btn btn-add" style="float:center;margin-bottom:32px;">CREATE ONE</button></a>
                        </td>
                        <td style="padding-left:40px;">
                            <a href="/"><button class="btn btn-back" style="float:center;margin-bottom:32px;">BACK</button></a>
                        </td>
                    </tr>
                </table>
            </div>
            <div class="col-md-3"></div>
        </div>

        {% else %}
            {% for place in places reversed %}
                <div class="row isi">
                    <div class="col-md-3"></div>
                    <div class="col-md-6" style="text-align:center;">
                        <div class="card mf">
                            <br>
                            <div class="card-header">
                                <h1 id="place">{{ place.place }}</h1>
                                <h id='date'>{{ place.date }}</h2>
                            </div>
                            <br><br>
                            <p id="desc">{{ place.desc }}</p>
                            <br>
                            <a class="btn btn-update" style="float: center;margin-bottom:32px;" href="{% url 'myfootprints:update-place' place.id %}">Edit</a>
                            <a class="btn btn-delete" style="float: center;margin-bottom:32px;" href="{% url 'myfootprints:delete-place' place.id %}">Remove</a>
                        </div>
                    </div>
                    <div class="col-md-3"></div>
                </div>
            {% endfor %}
        
        
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <table style="margin-right:auto;margin-left:auto;">
                    <tr>
                        <td>
                            <a href="{% url 'myfootprints:addfootprints' %}"><button class="btn btn-add" style="float:center;margin-bottom:32px;">ADD PLACE</button></a>
                        </td>
                        <td style="padding-left:40px;">
                            <a href="/"><button class="btn btn-back" style="float:center;margin-bottom:32px;">BACK</button></a>
                        </td>
                    </tr>
                </table>
            </div>
            <div class="col-md-3"></div>
        </div>
        {% endif %}

    </div>
</div>
{% endblock content %}