authapp/urls.py
from django.urls import path

from . import views

app_name = 'authapp'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('signin/', views.signin, name='signin'),
    path('logout/', views.logoutuser, name='logout'),
    path('profile/', views.profile, name='profile')
]

infocorona/urls.py
from django.urls import path

from . import views

app_name = 'infocorona'

urlpatterns = [
    path('info-corona/', views.info, name='info-new-user'),
    path('info-corona/data/', views.info_data, name='info-data'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

tkppwa05/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authapp.urls')),
    path('', include('about.urls')),
    path('', include('infocorona.urls')),
    path('', include('myfootprints.urls')),
    path('', include('covid19App.urls')),
]

infocorona/models.py
from django.db import models
from authapp.models import UserProfile
from django.utils import timezone

# Create your models here.
class Feeling(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE, null=True)
    date = models.DateField(default=timezone.now)
    feeling = models.TextField()

    def __str__(self):
        return self.feeling

infocorona/forms.py
from django import forms
from .models import Feeling

class FeelingForm(forms.ModelForm):
    
    class Meta:
        model = Feeling
        fields = ('feeling',)
        labels = {
            'feeling' : ''
        }
        widgets = {
            'feeling' : forms.Textarea(attrs={
                'id': 'feeling',
                'placeholder': ' I feel ...',
                'style': 'width: 100% ; background-color:#F7FBE1; border:0; font-family: "Poppins Light"; padding:5px; ',
                'cols':5, 'rows':5,
                },)
        }

infocorona/views.py
from django.shortcuts import render
from .models import Feeling
from .forms import FeelingForm
from authapp.models import UserProfile
from django.http import JsonResponse
from django.core import serializers
import json

# Create your views here.
def info(request):
    if request.user.is_authenticated:
        formFeeling = FeelingForm(request.POST or None)
        return render(request, 'info-corona-feel.html', {'formFeeling': formFeeling})
    return render(request, 'info-corona.html')

def info_data(request):
    if request.user.is_authenticated:
        u = UserProfile.objects.get(user=request.user)
        if request.method == 'POST':
            f = request.POST.get('feeling')
            Feeling.objects.create(user = u, feeling = f)
        
        feelings = Feeling.objects.all()
        obj = serializers.serialize('json', feelings)
        datas = json.loads(obj)
        for data in datas:
            id = data['fields']['user']
            data['fields']['user'] = UserProfile.objects.get(pk=id).full_name
    return JsonResponse(datas, safe=False)

infocorona/templates/info-corona-feel.html
{% extends 'info-corona.html' %}

{% block sign %}<li id="sign"><a href="{% url 'authapp:logout' %}">SIGN OUT</a></li>{% endblock %}

<!-- Form feeling about Corona -->
{% block feel %}
{% load static %}
<div class="feeling">
    <div class="panel panel-default col-md-6 col-md-offset-3">
        <div class="panel-body">
            <h2>How do you feel about this year pandemic?</h2><br>
            <form method="POST" id="feeling-form">
                {% csrf_token %}
                {{formFeeling.as_p}}
                <button type="submit" class="btn btn-submit">Submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock feel %}

infocorona/templates/info-corona.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Info Corona</title>
<link rel="stylesheet" href="{% static 'css/feelings.css' %}">
{% endblock meta %}

{% block sign %}<li id="sign"><a href="/auth/signin/">SIGN IN</a></li>{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="container">
        <div class="row info-corona">
            <div class="col-md-12">
                <h1>WHAT IS CORONA VIRUS?</h1>
                <br><br><br><br>
            </div>

            <div class="col-md-6 align-self-center">
                <img class="img-responsive img-center corona-img" src="{% static 'img/info-corona/Corona.svg'%}" alt="corona-img">
            </div>

            <div class="col-md-6">
                <p>Coronavirus disease (COVID-19) is an infectious disease caused by a newly discovered coronavirus.
 Most people infected with the COVID-19 virus will experience mild to moderate respiratory illness and recover without requiring special treatment.  Older people, and those with underlying medical problems like cardiovascular disease, diabetes, chronic respiratory disease, and cancer are more likely to develop serious illness.
 The best way to prevent and slow down transmission is to be well informed about the COVID-19 virus, the disease it causes and how it spreads. Protect yourself and others from infection by washing your hands or using an alcohol based rub frequently and not touching your face. The COVID-19 virus spreads primarily through droplets of saliva or discharge from the nose when an infected person coughs or sneezes, so it’s important that you also practice respiratory etiquette (for example, by coughing into a flexed elbow).</p>
                <p style="font-family:'Poppins Black';text-align:right;">Source: <a href="https://www.who.int/health-topics/coronavirus#tab=tab_1" target="_blank">WHO</a></p>
            </div>
            

            {% block feel %}
            {% endblock feel %}

            {% if user.is_authenticated %}
            <div class="col-md-12 info-corona">
                <h1>WHAT OTHERS FEEL </h1><br>
            </div>
            <div class="panel-data"></div>
            {% endif %}
        </div>
    </div>
</div>

<script type="text/javascript">
$(document).ready(function(){
    $('.btn-submit').on({
        mouseenter: function(){
            $(this).css("background-color", "#d6e67c");
        },
        mouseleave: function(){
            $(this).css("background-color", "#e8f3a6");
          }, 
        click: function(){
            $(this).css("background-color", "#d6e67c");
        },   
    })

    $('#feeling-form').on('submit', function(e){
        e.preventDefault();
        $.ajax({  
            type: 'POST',
            url: '/info-corona/data/',
            data: $('#feeling-form').serialize(),
            dataType : 'json',
            success: function(data){
                show_post();
                $('#feeling').val('');
            }
        })
    })

    show_post();
    function show_post(){
        $.ajax({
            url: '/info-corona/data/',
            success: function(data){
                $('.panel-data').empty();
                for (i = data.length-1; i >=0; i--){
                    var username = data[i].fields.user;
                    var feeling = data[i].fields.feeling;
                    var date = data[i].fields.date.split("-");
                    var mm = GetMonthName(date[1])
                    var panel = "<div class='feeling'><div class='panel panel-default col-md-6 col-md-offset-3'>" + 
                    "<div class='panel-body'>" + '<h4>' + username + '<small style="color:#404040">  on ' + 
                    Number(date[2]) + ' &nbsp;' + mm + ' &nbsp;' + date[0] + '</small></h4>' + '<p>' + feeling + '</p>'
                    + '</div></div></div>' ;
                    $('.panel-data').append(panel);
                }
            }
        })
    }
    function GetMonthName(monthNumber) {
        var months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
        return months[monthNumber - 1];
    }
})
</script>
{% endblock %}