main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

myfootprints/urls.py
from django.urls import path

from . import views

app_name = 'myfootprints'

urlpatterns = [
    path('my-footprints/', views.myfootprints, name='myfootprints'),
    path('add-place/', views. addplace, name='addfootprints'),
    path('delete-place/<int:id>', views.delete, name="delete-place"),
    path('update-place/<int:id>', views.update, name='update-place'),
]

tkppwa05/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authapp.urls')),
    path('', include('about.urls')),
    path('', include('infocorona.urls')),
    path('', include('myfootprints.urls')),
    path('', include('covid19App.urls')),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from authapp.models import UserProfile

def home(request):
    if request.user.is_authenticated:
        name = UserProfile.objects.get(user = request.user)
        data = {
            'name' : name
        }
        return render(request, 'main/home.html', data)
    else:
        return render(request, 'main/home-new-user.html')

main/templates/main/home-new-user.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Welcome to MyFootprints!</title>
{% endblock meta %}

{% block sign %}<li id="sign"><a href="/auth/signin/">SIGN IN</a></li>{% endblock %}

{% block content %}
<div class="container-fluid">
  <div class="container">
    </div class="row">

      <div class="col-md-6">
        <img class="img-responsive img-right people-img" src="{% static 'img/home-new-user/people-window.svg'%}" alt="people-window">
      </div>

      <div class="col-md-6 my-footprints-info">
        <div class="text-vertical-center">
          <br><br>
          <h1 style="margin-top:20px;">MY FOOTPRINTS</h1>
          <p>Note the last time you left home</p>
          <br><br>
          <a href="/auth/signup/" class="btn btn-start">START NOW</a>
        </div>
      </div>
        
    </div>
  </div>
</div>
{% endblock content %}

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Welcome, {{ name.full_name }}!</title>
<link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock meta %}

{% block content %}
  {% if user.is_authenticated %}
    <!-- <h1>Hello, {{ name.full_name }}</h1>
    <a href="/auth/logout/">logout</a> -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    
    <div class="container-fluid">
      <div class="container">
          <div class="row">

            <div class="col-md-6 welcomediv">
              <h1 id="welcome">Welcome</h1>
              <h1 id="name">{{ name.full_name }}</h1>
              <a href="{% url 'myfootprints:addfootprints' %}"><button class="btn btn-success">NOTE MY FOOTPRINTS</button></a>
              <a href="{% url 'myfootprints:myfootprints' %}"><button class="btn btn-outline-primary">MY FOOTPRINTS</button></a>
            </div>

            <div class="col-md-6">
              <img class="img-responsive boy-waving" src="{% static 'img/jendelahalo.svg' %}">
            </div>

          </div>
      </div>
    </div>
    
    <!--
    <div class="content">
        <div class="welcomediv">
            <h1 id="welcome">Welcome</h1>
            <h1 id="name">{{ name.full_name }}</h1>
            <form method="get" action="">
                <button class="btn btn-success" type="submit">NOTE MY FOOTPRINTS</button>
            </form>
            <form method="get" action="">
                <button class="btn btn-outline-primary" type="submit">MY FOOTPRINTS</button>
            </form>
        </div>
        <div>
            <img src="{% static 'img/jendelahalo.svg' %}">
        </div>
    </div> -->
  {% else %}
    <div class="container-fluid">
        <div class="container">
          </div class="row">

            <div class="col-md-6">
              <img class="img-responsive img-right people-img" src="{% static 'img/home-new-user/people-window.svg'%}" alt="people-window">
            </div>

            <div class="col-md-6 my-footprints-info">
              <div class="text-vertical-center">
              <br><br>
              <h1 style="margin-top:20px;">MY FOOTPRINTS</h1>
              <p>Note the last time you left home</p>
              <br><br>
              <a href="/auth/signup/" class="btn btn-start">START NOW</a>
            </div>
          </div>
        
        </div>
      </div>
    </div>
  {% endif %}
{% endblock content %}